name: login-and-install
description: "Login to NPM, install dependencies, download local.settings.json"
inputs:
  token:
    description: 'NPM Token'
    required: true
  settings:
    description: 'Local settings json file'
    required: true
  repo:
    description: "Name of the repo calling this action"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: NPM login
      run: echo '//registry.npmjs.org/:_authToken=${{ inputs.token }}' > ~/.npmrc
      shell: bash
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Add local.settings.json
      run: echo '${{ inputs.settings }}' > '/home/runner/work/${{ inputs.repo }}/${{ inputs.repo }}/local.settings.json'
      shell: bash
