name: login-and-install
description: "Login to NPM, install dependencies, download local.settings.json"
inputs:
  token:
    description: 'NPM Token'
    required: true
  settings:
    description: 'Local settings json file'
    required: true
  repo:
    description: "Name of the repo calling this action"
    required: true
  branch:
    description: "branch to use for the run"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - if: ${{ !inputs.branch }}
      name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - if: ${{ inputs.branch }}
      name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.branch }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: NPM login
      run: echo '//registry.npmjs.org/:_authToken=${{ inputs.token }}' > ~/.npmrc
      shell: bash
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Add local.settings.json
      run: echo '${{ inputs.settings }}' > '/home/runner/work/${{ inputs.repo }}/${{ inputs.repo }}/local.settings.json'
      shell: bash
